
### GET ALL ####
GET http://localhost:3300/subscribers

### GET ONE ####
GET  http://localhost:3300/subscribers/609665f9a540393d1aaffd8d


### POST - Valid ####
POST http://localhost:3300/subscribers
Content-Type: application/json

{
    "name": "Sharma",
    "subscribedToChannel": "Traversy Media"
}
/*
{
    "name": "Chetan",
    "subscribedToChannel": "Web Dev simplifid"
}
{
    "name": "Sharma",
    "subscribedToChannel": "Traversy Media"
}
{
    "name": "India",
    "subscribedToChannel": "Great India!"
}
*/

### POST - Invalid ####

POST http://localhost:3300/subscribers
Content-Type: application/json

{
    "subscribedToChannel": "Web Dev Simplified"
}

### PATCH ONE ####
PATCH  http://localhost:3300/subscribers/609665f9a540393d1aaffd8d
Content-Type: application/json

{
    "name" : "Sharma Chetan"
}


### DELETE ONE ####
DELETE  http://localhost:3300/subscribers/6096648143157f3c6aec3abb
